server.port=${PORT:8080}

spring.application.name=gateway-service

user.service.url=${USER_SERVICE_URL}
trip.service.url=${TRIP_SERVICE_URL}
ai.itinerary.service.url=${AI_ITINERARY_SERVICE_URL}

jwt.secret=${JWT_SECRET}

management.endpoints.web.exposure.include=health,info,gateway